
const videoListTypes = {
  SET_VIDEO_LIST : 'SET_VIDEO_LIST',
  SAVE_VIDEO: 'SAVE_VIDEO',
  SET_ORIGINAL_VIDEO: 'SET_ORIGINAL_VIDEO',
  PLAY_VIDEO_FROM_LIST: 'PLAY_VIDEO_FROM_LIST',
  OPEN_EDIT_VIDEO: 'OPEN_EDIT_VIDEO',
  FILTER_VIDEOS_BY_TAG: 'FILTER_VIDEOS_BY_TAG'
}

export default videoListTypes;